### ISSUE TITLE
Add support for compiling tight list-items

### ISSUE THREAD

**Issue by tmcw** [wooorm/mdast-toc#1]
This produces the following markdown:

```md
*   [Usage](#usage)

*   [API](#api)

    *   [mdast.use(toc, options)](#mdastusetoc-options)

*   [License](#license)
```

Which looks like

*   [Usage](#usage)

*   [API](#api)

    *   [mdast.use(toc, options)](#mdastusetoc-options)

*   [License](#license)

But could it produce

```md
*   [Usage](#usage)
*   [API](#api)
    *   [mdast.use(toc, options)](#mdastusetoc-options)
*   [License](#license)
```

Which looks like the more compact

*   [Usage](#usage)
*   [API](#api)
    *   [mdast.use(toc, options)](#mdastusetoc-options)
*   [License](#license)

?

**Comment by wooorm** [comment]
Thanks for letting me know, hope this fixes things for you!
