### ISSUE TITLE
usage from an AST

### ISSUE THREAD

**Issue by tmcw** [wooorm/mdast-toc#2]
I'm generating an AST for a Markdown file and would like to use mdast-toc to add a table of contents, but it seems like this will only work when processing an existing markdown file, rather than generating one from scratch. Should I generate into a file and then re-transform it, or is there a way to use a transformer without starting out with a file?

**Comment by wooorm** [comment]
Sorry, I'm on my mobile rather than my mac, so you'll have to do without links: use mdast.parse together with mdast.run, that should do the trick without a file!

**Comment by wooorm** [comment]
Here are the links for [`mdast.parse`](https://github.com/wooorm/mdast/blob/master/doc/mdast.3.md#mdastparsefile-options) and [`mdast.run`](https://github.com/wooorm/mdast/blob/master/doc/mdast.3.md#mdastrunnode-file-done), hope that makes it a bit more clear. You won’t need a file for that, if you’d like to get access to that you’ll have to pass a `done` callback to `mdast.run` which receives a file as a parameter.
